// <auto-generated />
namespace E_Com_Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Ecom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ecom));
        
        string IMigrationMetadata.Id
        {
            get { return "202004291115322_E-com"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
